matrix:
  PLATFORM_ARCHI:
    - linux/arm
    - linux/amd64
platform: ${PLATFORM_ARCHI}

pipeline:
  # Publish the amd64 docker container
  docker-amd64:
    group: docker
    image: plugins/docker
    dockerfile: Dockerfile-amd64
    repo: tellu/alpine-build-base
    auto_tag: true
    auto_tag_suffix: amd64
    secrets: [ docker_username, docker_password ]
    when:
      platform: linux/amd64
    
  # Publish the arm32v6 docker container
  docker-arm32v6:
    group: docker
    image: plugins/docker
    dockerfile: Dockerfile-arm32v6
    repo: tellu/alpine-build-base
    auto_tag: true
    auto_tag_suffix: arm32v6
    secrets: [ docker_username, docker_password ]
    when:
      platform: linux/arm